services:
  api-calculator:
    image: ghcr.io/ndoy3m4n/api-calculator:latest
    container_name: rest-server
    build:
      context: .
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DBSTRING=${GOOSE_DBSTRING}
    ports:
      - 3000:3000
    deploy:
      restart_policy:
        condition: on-failure
