components:
  schemas:
    main.APIError:
      properties:
        error:
          type: string
      type: object
    main.APILoginSuccess:
      properties:
        token:
          type: string
      type: object
    main.APISuccess:
      properties:
        result:
          type: number
      type: object
    main.Payload:
      properties:
        number1:
          example: 6
          type: number
        number2:
          example: 9
          type: number
      type: object
    main.PayloadLogin:
      properties:
        pseudo:
          example: p4p1
          type: string
      type: object
  securitySchemes:
    bearerauth:
      bearerFormat: JWT
      scheme: bearer
      type: http
externalDocs:
  description: ""
  url: ""
info:
  contact:
    email: pa.ndoye@outlook.com
    name: Abdoulaye NDOYE
    url: https://github.com/NDOY3M4N
  description: This is a simple server for Calculator API
  license:
    name: MIT
    url: https://github.com/NDOY3M4N/api-calculator/blob/main/LICENSE.md
  title: Calculator API
  version: "1.0"
openapi: 3.1.0
paths:
  /add:
    post:
      description: Add two numbers together
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/main.Payload'
        description: Numbers needed for the operation
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APISuccess'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APIError'
          description: Bad Request
      security:
      - BearerAuth: []
      summary: Add two numbers
      tags:
      - Math
  /divide:
    post:
      description: Divide two numbers together
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/main.Payload'
        description: Numbers needed for the operation
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APISuccess'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APIError'
          description: Bad Request
      security:
      - BearerAuth: []
      summary: Divide two numbers
      tags:
      - Math
  /login:
    post:
      description: Log the user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/main.PayloadLogin'
        description: Field needed for login
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APILoginSuccess'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APIError'
          description: Bad Request
      summary: Login
      tags:
      - User
  /multiply:
    post:
      description: Multiply two numbers together
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/main.Payload'
        description: Numbers needed for the operation
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APISuccess'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APIError'
          description: Bad Request
      security:
      - BearerAuth: []
      summary: Multiply two numbers
      tags:
      - Math
  /substract:
    post:
      description: Substract two numbers together
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/main.Payload'
        description: Numbers needed for the operation
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APISuccess'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APIError'
          description: Bad Request
      security:
      - BearerAuth: []
      summary: Substract two numbers
      tags:
      - Math
  /sum:
    post:
      description: Add all numbers in an array
      requestBody:
        content:
          application/json:
            schema:
              items:
                type: number
              type: array
        description: Array of numbers needed for the operation
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APISuccess'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/main.APIError'
          description: Bad Request
      security:
      - BearerAuth: []
      summary: Sum numbers
      tags:
      - Math
servers:
- description: Development server
  url: http://localhost:3000/api/v1
